<?xml version="1.0" encoding="ISO-8859-1"?>

<xsl:stylesheet 
  version="1.0"
  xmlns:date="http://exslt.org/dates-and-times"
  xmlns:b2h="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  exclude-result-prefixes="date b2h xsl">
<!--   xmlns="http://www.w3.org/TR/html4/loose.dtd"  -->

<xsl:import href="external/date.format-date.template.xsl" />

<xsl:output 
  method="html" 
  version="4.0"
  doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
  doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
  encoding="utf-8" 
  indent="yes"/>

<xsl:strip-space elements="b2h:size b2h:file_format b2h:exists b2h:datetime" />

<xsl:template match="b2h:main_index_links">
  <div id="b2hLinkIndex">
  <xsl:for-each select="b2h:index_link">
    <a>
    <xsl:attribute name="href">
     <xsl:value-of select="b2h:url" />
    </xsl:attribute>
    <xsl:value-of select="b2h:name"/>
   </a>
  </xsl:for-each>
  </div>
</xsl:template>

<!-- A template to format the number of bytes into something a little more human
     readable -->
<xsl:template name="size" match="b2h:size">
 <xsl:choose>
  <xsl:when test=".&gt;1024*1024*1024">
   <xsl:value-of select="format-number(. div (1024*1024*1024), '#.0')" />GB
  </xsl:when>
  <xsl:when test=".&gt;1024.0*1024.0">
   <xsl:value-of select="format-number(. div (1024*1024), '#.0')" />MB
  </xsl:when>
  <xsl:when test=".&gt;1024.0">
   <xsl:value-of select="format-number(. div (1024), '#.0')" />kB
  </xsl:when>
  <xsl:otherwise>
   <xsl:value-of select="format-number(. , '#')" />kB
  </xsl:otherwise>
 </xsl:choose>
</xsl:template>

<!-- A long format of download links, to be used with call-template -->
<xsl:template name="dl_link_long">
 <xsl:param name="dl" />
 <xsl:choose>
  <xsl:when test="count($dl/b2h:download_entry[b2h:exists=1 or b2h:exists='true']) != 0">
   <xsl:for-each select="$dl/b2h:download_entry">
    <xsl:if test="b2h:exists=1 or b2h:exists='true'">
     <a>
      <xsl:attribute name="href">
       <xsl:value-of select="b2h:url" />
      </xsl:attribute>
      <xsl:choose>
       <xsl:when test="b2h:file_format='pdf'">[PDF]</xsl:when>
       <xsl:when test="b2h:file_format='ps.gz'">[gzipped postscript]</xsl:when>
       <xsl:when test="b2h:file_format='ps'">[postscript]</xsl:when>
       <xsl:when test="b2h:file_format='html'">[HTML]</xsl:when>
       <xsl:when test="b2h:file_format='supplemental.pdf'">[Supplemental Material]</xsl:when>
       <xsl:otherwise>[unknown format]
        <xsl:message>Warning: Unknown file format: <xsl:value-of select="b2h:file_format" /></xsl:message>
       </xsl:otherwise>
      </xsl:choose>
     </a> 
     <xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
    </xsl:if>
   </xsl:for-each>
  </xsl:when>
  <xsl:otherwise>
  (unavailable)
  </xsl:otherwise>
 </xsl:choose>
</xsl:template>

<!-- A short format of download links, to be used with call-template -->
<xsl:template name="dl_link_short">
 <xsl:param name="dl" />
 <xsl:choose>
  <xsl:when test="count($dl/b2h:download_entry[b2h:exists=1 or b2h:exists='true']) != 0">
   <xsl:for-each select="$dl/b2h:download_entry">
    <xsl:if test="b2h:exists=1 or b2h:exists='true'">
     <a>
      <xsl:attribute name="href">
       <xsl:value-of select="b2h:url" />
      </xsl:attribute>
      <xsl:choose>
       <xsl:when test="b2h:file_format='pdf'">[PDF]</xsl:when>
       <xsl:when test="b2h:file_format='ps.gz'">[gzipped postscript]</xsl:when>
       <xsl:when test="b2h:file_format='ps'">[postscript]</xsl:when>
       <xsl:when test="b2h:file_format='html'">[HTML]</xsl:when>
       <xsl:when test="b2h:file_format='supplemental.pdf'">[Supplemental Material]</xsl:when>
       <xsl:otherwise>[unknown format]
        <xsl:message>Warning: Unknown file format: <xsl:value-of select="b2h:file_format" /></xsl:message>
       </xsl:otherwise>
      </xsl:choose>
     </a> 
     <xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
    </xsl:if>
   </xsl:for-each>
  </xsl:when>
  <xsl:otherwise>
  (unavailable)
  </xsl:otherwise>
 </xsl:choose>
</xsl:template>

<!-- Template for the crediting of the generated info -->
<xsl:template match="b2h:generation_info">
 <div id="b2hInfo">
 Generated by
 <a>
  <xsl:attribute name="href">
   <xsl:value-of select="b2h:program_url" />
  </xsl:attribute>
  <xsl:value-of select="b2h:program" />
 </a>
 (written by <a>
  <xsl:attribute name="href">
   <xsl:value-of select="b2h:author_url" />
  </xsl:attribute>
  <xsl:value-of select="b2h:author" />
  </a>) on
  <xsl:call-template name="date:format-date">
   <xsl:with-param name="date-time" select="b2h:datetime" />
   <xsl:with-param name="pattern" select="'EEE MMM dd, yyyy HH:mm:ss'" />
  </xsl:call-template>
 </div>
</xsl:template>

<xsl:template name="paper_info_short">
 <xsl:param name="paper_info" />
  <xsl:value-of select="$paper_info/b2h:citationtitlefirst" disable-output-escaping="yes"/>
  <div class="b2hInfoShort">&#187;
  <xsl:if test="$paper_info/b2h:detail_url">
   <a>
    <xsl:attribute name="href"><xsl:value-of select="$paper_info/b2h:detail_url" /></xsl:attribute>
    Details
   </a>
   <xsl:text disable-output-escaping="yes">&amp;nbsp;&amp;nbsp;&amp;nbsp;</xsl:text>
  </xsl:if>
  <xsl:if test="$paper_info/b2h:bibtex_url">
   <a>
    <xsl:attribute name="href"><xsl:value-of select="$paper_info/b2h:bibtex_url" /></xsl:attribute>
    BibTeX
   </a>
   <xsl:text disable-output-escaping="yes">&amp;nbsp;&amp;nbsp;&amp;nbsp;</xsl:text>
  </xsl:if>
  Download: 
  <xsl:call-template name="dl_link_short">
   <xsl:with-param name="dl" select="$paper_info/b2h:download_links" />
  </xsl:call-template>
  </div>
</xsl:template>

<!-- Note that this template does NOT print a header for this group. You should
     do that before applying this template -->
<xsl:template match="b2h:group_papers">
 <ul class="b2hGroupPapers">
   <xsl:for-each select="b2h:paper_info">
  <li>
   <xsl:call-template name="paper_info_short">
    <xsl:with-param name="paper_info" select="." />
   </xsl:call-template>
  </li>
 </xsl:for-each>
 </ul>
</xsl:template>

<!--  The main template to match for a list of paper page -->
<!-- Note that this is a named template you have to call with call-template -->
<xsl:template name="list_papers_with_sep">
 <xsl:param name="list" />
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=utf-8" />
    <meta name="author" content="Michael Bowling" />
    <link rel="stylesheet" type="text/css" href="../style.css"/>

    <title>Michael Bowling's Publications</title>
  </head>

  <body>
    <div id="top"></div>
  
    <!-- ###### Header ###### -->

    <div id="header">
      <span class="headerTitle">Michael Bowling</span>
      <div class="addressBlock">
	Associate Professor <br/>
	<a href="http://www.cs.ualberta.ca">Department of Computing Science</a><br/>
	<a href="http://www.ualberta.ca">University of Alberta</a> <br/>
	Edmonton, Alberta <br/>
	Canada T6G 2E8 
      </div>

      <div class="addressBlock2">
	Office: 339 Athabasca Hall <br/>
	Email: bowling *AT* cs.ualberta.ca <br/>
	Phone: (780) 492-1766 <br/>
	Fax: (780) 492-1071 
      </div>
</div>

    <!-- ###### Side Boxes ###### -->

    <div class="sideBox LHS">
      <a href="../index.html">&#8250; Main Page</a>
      <span class="thisPage">&#187; Publications</span>
      <a href="../research.html">&#8250; Research</a>
      <a href="../calendar.html">&#8250; Calendar</a>
      <a href="../cv.html">&#8250; CV</a>
      <a href="../personal.html">&#8250; Personal</a>
    </div>

    <!-- ###### Body Text ###### -->

    <div class="sideBox LHS">
      <div>Skip To</div>
      <xsl:for-each select="$list/b2h:list_group_papers/b2h:group_papers">
	<a>
	  <xsl:attribute name="href">#<xsl:value-of select="b2h:group_title" /></xsl:attribute>
	  <xsl:value-of select="b2h:group_title" disable-output-escaping="yes"/>
<!--	  (<xsl:value-of select="count(child::*[position()>1])"/>) -->
	</a>
      </xsl:for-each>
    </div>

    <div id="bodyText">

  <xsl:apply-templates select="$list/b2h:main_index_links" />

  <xsl:for-each select="$list/b2h:list_group_papers/b2h:group_papers">
    <xsl:if test="position() != 1"><a class="topOfPage" href="#top" title="Top Of Page">top</a></xsl:if>

   <h1>
    <a>
     <xsl:attribute name="name"><xsl:value-of select="b2h:group_title" /></xsl:attribute>    
    </a>
    <xsl:value-of select="b2h:group_title" disable-output-escaping="yes"/>
   </h1>
   <xsl:apply-templates select="." />
  </xsl:for-each>  

  <xsl:apply-templates select="$list/b2h:generation_info" />

    </div>
    
    <!-- ###### Footer ###### -->

    <div id="footer">
      <div class="footerLHS">
        <a href="http://validator.w3.org/check/referer">Valid XHTML 1.0 Strict</a>
      </div>
      
      <div class="footerLHS">
        <a href="http://jigsaw.w3.org/css-validator/check/referer">Valid CSS 2</a>
      </div>
      
      <div>
        Website design adapted from <a href="http://www.oswd.org/design/preview/id/1152">Blue Haze</a> by <a href="http://www.oswd.org/email.phtml?user=haran">haran</a>
      </div>

      <div>
	Thanks to <a href="http://www.oswd.org">Open Source Web Development</a>
      </div>
    </div>
  </body>
</html>
</xsl:template>

<!--  The main template to match for a list of paper page with the group boundaries ignored -->
<!-- Note that this is a named template you have to call with call-template -->
<xsl:template name="list_papers_no_sep">
 <xsl:param name="list" />
 <html lang="en" xml:lang="en">
 <head>
  <title>Patrick F. Riley: Publications <xsl:value-of select="$list/b2h:list_title" /></title>
  <link rel="StyleSheet" href="../pfrstyle.css" type="text/css" />              
  <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1"/>
 </head>
 <body>
  <h1>Patrick F. Riley's Publications</h1>

  <xsl:apply-templates select="$list/b2h:main_index_links" />

  <h2> <xsl:value-of select="$list/b2h:list_title"/> </h2>

  <hr width="100%" size="2"/>

  <ul>
   <xsl:for-each select="$list/b2h:list_group_papers/b2h:group_papers/b2h:paper_info">
    <li>
     <xsl:call-template name="paper_info_short">
      <xsl:with-param name="paper_info" select="." />
     </xsl:call-template>
    </li>
   </xsl:for-each>  
  </ul>

  <hr width="100%" size="2"/>
  <p><small>
  <xsl:apply-templates select="$list/b2h:generation_info" />
  </small> </p>

 </body>
 </html>
</xsl:template>

<!--  The main template to match for a paper detail page -->
<xsl:template match="b2h:paper_detail">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=utf-8" />
    <meta name="author" content="Michael Bowling" />
  <link rel="StyleSheet" href="../style.css" type="text/css" />              
    <title>Michael Bowling's Publications</title>
  </head>

  <body>
    <div id="top"></div>
  
    <!-- ###### Header ###### -->

    <div id="header">
      <span class="headerTitle">Michael Bowling</span>
      <div class="addressBlock">
	Associate Professor <br/>
	<a href="http://www.cs.ualberta.ca">Department of Computing Science</a><br/>
	<a href="http://www.ualberta.ca">University of Alberta</a> <br/>
	Edmonton, Alberta <br/>
	Canada T6G 2E8 
      </div>

      <div class="addressBlock2">
	Office: 339 Athabasca Hall <br/>
	Email: bowling *AT* cs.ualberta.ca <br/>
	Phone: (780) 492-1766 <br/>
	Fax: (780) 492-1071 
      </div>
</div>

    <!-- ###### Side Boxes ###### -->

    <div class="sideBox LHS">
      <a href="../index.html">&#8250; Main Page</a>
      <a href="sort_date.html">&#8250; Publications</a>
      <span class="thisPage">&#8195; &#187; Details</span>
      <a href="../cv.html">&#8250; CV</a>
      <a href="../calendar.html">&#8250; Calendar</a>
      <a href="../research.html">&#8250; Research</a>
      <a href="../personal.html">&#8250; Personal</a>
    </div>

    <!-- ###### Body Text ###### -->

    <div id="bodyText">


    <h1> <xsl:value-of select="b2h:paper_info/b2h:title" disable-output-escaping="yes"/> </h1>

   <p class="citation">
   <xsl:value-of select="b2h:paper_info/b2h:citation" disable-output-escaping="yes" /> 
   </p>	

   <h2>Download</h2>
   <p>
    <xsl:call-template name="dl_link_long">
     <xsl:with-param name="dl" select="b2h:paper_info/b2h:download_links" />
    </xsl:call-template>
   </p>

   <h2>Abstract</h2>
   <div class="abstract">
    <xsl:choose>
     <xsl:when test="b2h:paper_info/b2h:abstract">
      <xsl:value-of select="b2h:paper_info/b2h:abstract" disable-output-escaping="yes" /> 
     </xsl:when>
     <xsl:otherwise>
      (unavailable)
     </xsl:otherwise>
    </xsl:choose>
   </div>

   <xsl:if test="b2h:paper_info/b2h:errata">
    <h2>Errata</h2>
    <p><xsl:value-of select="b2h:paper_info/b2h:errata" disable-output-escaping="yes" /></p>
   </xsl:if>

   <xsl:if test="b2h:paper_info/b2h:extra_info">
    <h2>Additional Information</h2>
    <p><xsl:value-of select="b2h:paper_info/b2h:extra_info" disable-output-escaping="yes" /></p>
   </xsl:if>

   <xsl:choose>
    <xsl:when test="b2h:paper_info/b2h:bibtex_url">
     <a>
      <xsl:attribute name="href"><xsl:value-of select="b2h:paper_info/b2h:bibtex_url" /></xsl:attribute>
      <h3>BibTeX</h3>
     </a>
    </xsl:when>
    <xsl:otherwise>
     <h3>BibTeX Entry</h3>
    </xsl:otherwise>
   </xsl:choose>
   <xsl:choose>
    <xsl:when test="b2h:paper_info/b2h:bibtex_entry">
     <pre>
      <xsl:value-of select="b2h:paper_info/b2h:bibtex_entry"/> 
     </pre>
    </xsl:when>
    <xsl:otherwise>
     (unavailable)
    </xsl:otherwise>
   </xsl:choose>

   <p><small>
   <xsl:apply-templates select="b2h:generation_info" />
   </small> </p>

    </div>
    
    <!-- ###### Footer ###### -->

    <div id="footer">
      <div class="footerLHS">
        <a href="http://validator.w3.org/check/referer">Valid XHTML 1.0 Strict</a>
      </div>
      
      <div class="footerLHS">
        <a href="http://jigsaw.w3.org/css-validator/check/referer">Valid CSS 2</a>
      </div>
      
      <div>
        Website design adapted from <a href="http://www.oswd.org/design/preview/id/1152">Blue Haze</a> by <a href="http://www.oswd.org/email.phtml?user=haran">haran</a>
      </div>

      <div>
	Thanks to <a href="http://www.oswd.org">Open Source Web Development</a>
      </div>
    </div>
  </body>
</html>
</xsl:template>

<!--  The main templates for the list of papers pages -->

<xsl:template match="b2h:list_papers_by_default">
 <xsl:call-template name="list_papers_no_sep">
  <xsl:with-param name="list" select="." />
 </xsl:call-template>
</xsl:template>

<xsl:template match="b2h:list_papers_by_date">
 <xsl:call-template name="list_papers_with_sep">
  <xsl:with-param name="list" select="." />
 </xsl:call-template>
</xsl:template>

<xsl:template match="b2h:list_papers_by_author">
 <xsl:call-template name="list_papers_with_sep">
  <xsl:with-param name="list" select="." />
 </xsl:call-template>
</xsl:template>

<xsl:template match="b2h:list_papers_by_author_class">
 <xsl:call-template name="list_papers_with_sep">
  <xsl:with-param name="list" select="." />
 </xsl:call-template>
</xsl:template>

<xsl:template match="b2h:list_papers_by_pubtype">
 <xsl:call-template name="list_papers_with_sep">
  <xsl:with-param name="list" select="." />
 </xsl:call-template>
</xsl:template>

<xsl:template match="b2h:list_papers_by_rescat">
 <xsl:call-template name="list_papers_with_sep">
  <xsl:with-param name="list" select="." />
 </xsl:call-template>
</xsl:template>

<xsl:template match="b2h:list_papers_by_funding">
 <xsl:call-template name="list_papers_with_sep">
  <xsl:with-param name="list" select="." />
 </xsl:call-template>
</xsl:template>

</xsl:stylesheet>
